default:
  resource:
    - from_path: "./stock.db"
      to_path: "/data/stock.db"
    - from_path: "./portfolio.db"
      to_path: "/data/portfolio.db"
  content:
    - name: "Stock Portfolio Report"
      path: "./report-portfolio"
      description: "This parameterized rmarkdown report illustrates scheduled, customized emails and user-editable parameterization of reporting"
      tag: "Demo Content|Stock Portfolio"
      url: "/stock-portfolio-report/"
    - name: "Stock Portfolio Shiny Application"
      path: "./shiny-app"
      description: "This Shiny application allows interactive exploration of portfolio returns along with tuning of model parameters"
      tag: "Demo Content|Stock Portfolio"
      url: "/stock-portfolio-app/"
    - name: "Stock Information Plumber API"
      path: "./api"
      description: "This Plumber API surfaces the ability to programmatically request price history or a number representing the relative volatility of a stock ticker"
      tag: "Demo Content|Stock Portfolio"
      url: "/stock-portfolio-api/"
